import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * Mirrors the shipped client weapon template table
 * (`Assets/_Game/SettingGen/Item/Weapon.asset`, generated by
 * `FileWeaponItemBaseReader.GenAsset` from `Item/Weapon.txt`) as far as the
 * weapon inspect page (`UI_WeaponInfo`) is concerned.
 *
 * The client builds instance skill slots from the `skillinfo` field (proto
 * field 11, repeated `MiniSkill`) of `gsproto.ItemInfo` inside
 * `EquipManager.AddWeapon`:
 *
 * - skilltype 1 -> `WeaponItem.MainSkillLevel` (not sent; battle-only);
 * - skilltype 2 -> `passiveskill[i]` / `passiveskilllevel[i]` (config
 *   passive skills, what the inspect page renders);
 * - skilltype 4 -> `recastskill[i]` / `recastskilllevel[i]` (recast skills;
 *   recast is unimplemented, so none are sent).
 *
 * A weapon's passive skills come from its template `PassiveSkill1` /
 * `PassiveSkill2` and their level is raised by 1 per breakthrough
 * (`WeaponCommon:GetMaxSkillLevel`, in-game tip
 * “武器的技能在「突破」时会相应提升1级”), so skill level = breakLevel + 1.
 */

export const WEAPON_GENRE = 2;

export const WEAPON_SKILL_TYPE_PASSIVE = 2;

export interface WeaponTemplate {
  rarity: number;
  passiveSkill1: number;
  passiveSkill2: number;
}

export interface WeaponSkillInfo {
  skillId: number;
  skillLevel: number;
  skillType: number;
}

export class WeaponTemplateCatalog {
  #templates = new Map<string, WeaponTemplate>();

  private constructor() {}

  static loadDefault(): WeaponTemplateCatalog {
    const file = path.resolve(process.cwd(), "resources/weapon/weapons.txt");
    return WeaponTemplateCatalog.load(readFileSync(file, "utf8"));
  }

  static load(contents: string): WeaponTemplateCatalog {
    const catalog = new WeaponTemplateCatalog();
    const lines = contents.split(/\r?\n/).slice(3);
    for (const line of lines) {
      if (!line.trim()) continue;
      const columns = line.split("\t");
      if (columns.length < 7) {
        throw new Error(`Malformed weapon template row: ${line}`);
      }
      const [genre, detail, particular, level, rarity, passiveSkill1, passiveSkill2] =
        columns.map((column) => Number(column));
      if (
        ![genre, detail, particular, level, rarity, passiveSkill1, passiveSkill2].every(
          (value) => Number.isSafeInteger(value),
        )
      ) {
        throw new Error(`Malformed weapon template row: ${line}`);
      }
      catalog.#templates.set([genre, detail, particular, level].join(":"), {
        rarity: rarity!,
        passiveSkill1: passiveSkill1!,
        passiveSkill2: passiveSkill2!,
      });
    }
    return catalog;
  }

  get size(): number {
    return this.#templates.size;
  }

  templateOf(
    genre: number,
    detail: number,
    particular: number,
    level: number,
  ): WeaponTemplate | null {
    return this.#templates.get([genre, detail, particular, level].join(":")) ?? null;
  }
}

let defaultCatalog: WeaponTemplateCatalog | null = null;

export function weaponTemplateCatalog(): WeaponTemplateCatalog {
  defaultCatalog ??= WeaponTemplateCatalog.loadDefault();
  return defaultCatalog;
}

/**
 * Instance passive skills for the given weapon, ready to be serialized into
 * `ItemInfo.skillinfo`. Returns an empty list for non-weapons and for
 * templates without config passive skills.
 */
export function weaponPassiveSkills(
  genre: number,
  detail: number,
  particular: number,
  level: number,
  breakLevel: number,
  catalog: WeaponTemplateCatalog = weaponTemplateCatalog(),
): WeaponSkillInfo[] {
  if (genre !== WEAPON_GENRE) return [];
  const template = catalog.templateOf(genre, detail, particular, level);
  if (!template) return [];
  const skillLevel = breakLevel + 1;
  return [template.passiveSkill1, template.passiveSkill2]
    .filter((skillId) => skillId > 0)
    .map((skillId) => ({
      skillId,
      skillLevel,
      skillType: WEAPON_SKILL_TYPE_PASSIVE,
    }));
}
